if ccache not found, set default AOMP_USE_CACHE to 0 if not already set.  Also fix problem when AOMP/../bin/mygpu is not found to avoid bash fail

diff --git a/bin/aomp_common_vars b/bin/aomp_common_vars
--- a/bin/aomp_common_vars
+++ b/bin/aomp_common_vars
@@ -49,14 +49,19 @@ fi
 # all the test repositories in a different directory.
 AOMP_REPOS_TEST=${AOMP_REPOS_TEST:-$HOME/git/aomp-test}
 
+_ccache_bin=`which ccache`
+if [ "$_ccache_bin" == "" ] ; then
+AOMP_USE_CCACHE=${AOMP_USE_CCACHE:-0}
+else
 AOMP_USE_CCACHE=${AOMP_USE_CCACHE:-1}
+fi
 if [ "$AOMP_USE_CCACHE" == 0 ] ; then
   AOMP_CCACHE_OPTS=""
 else
   _ccache_bin=`which ccache`
   if [ "$_ccache_bin" == "" ] ; then
     echo "ERROR: AOMP_USE_CCACHE is $AOMP_USE_CCACHE but no ccache bin found in PATH"
-    echo "       Either install ccache or set AOMP_USE_CCACHE=0"
+    echo "       Either fix path,  install ccache, or set AOMP_USE_CCACHE=0"
     echo
     exit 1
   fi
@@ -521,8 +526,12 @@ function setaompgpu (){
       detected_gpu=$($AOMP/bin/amdgpu-arch)
       detected_gpu=$(echo $detected_gpu | awk '{print $1,$5}')
       detected_gpu=`echo $detected_gpu | cut -d" " -f1` # pick first found
-    else
+    elif [ -e $AOMP/../bin/mygpu ]; then
       detected_gpu=$($AOMP/../bin/mygpu)
+    else
+      echo "Error: in setaompgpu, could not find rocm_agent_enumerator"
+      echo "       Set AOMP_GPU, AOMP, or install ROCm"
+      exit 1
     fi
   fi
 
