add gfx1010 . Set default for OAMP_USE_NINJA to 0 and if it is set, check for ninja binary because we do not have ninja as a build requirement

diff --git a/bin/aomp_common_vars b/bin/aomp_common_vars
--- a/bin/aomp_common_vars
+++ b/bin/aomp_common_vars
@@ -80,6 +80,19 @@ if [ -f /usr/local/cmake/bin/cmake ] ; then
 else
   AOMP_CMAKE=${AOMP_CMAKE:-cmake}
 fi
+
+AOMP_USE_NINJA=${AOMP_USE_NINJA:-0}
+if [ "$AOMP_USE_NINJA" == 0 ] ; then
+  AOMP_NINJA_BIN="make"
+else
+  AOMP_NINJA_BIN=`which ninja`
+  if [ AOMP_NINJA_BIN == "" ] ; then
+    echo "ERROR: AOMP_USE_NINJA is $AOMP_USE_NINJA but no ninja bin found in PATH"
+    echo "       Either install ninja in PATH or set AOMP_USE_NINJA=0"
+    echo
+    exit 1
+  fi
+fi
 AOMP_PROC=`uname -m`
 if [ "$AOMP_PROC" == "unknown" ] ; then
    AOMP_PROC=`uname -a | awk '{print $(NF-1)}'`
@@ -145,7 +158,7 @@ fi
 
 # Set list of default amdgcn subarchitectures to build
 # Developers may override GFXLIST to shorten build time.
-GFXLIST=${GFXLIST:-"gfx700 gfx701 gfx801 gfx803 gfx900 gfx902 gfx906 gfx908 gfx90a gfx1030 gfx1031"}
+GFXLIST=${GFXLIST:-"gfx700 gfx701 gfx801 gfx803 gfx900 gfx902 gfx906 gfx908 gfx90a gfx1010 gfx1030 gfx1031"}
 export GFXLIST
 
 # Calculate the number of threads to use for make
