This is a major upgrade to build_supp.sh for building supplemental components in AOMP_SUPP. We add a symbolic link from build_prereq.sh to be used or building all prerequisite components outside the compiler installation.  This will reduce compiler footprint. The current prequisite components are cmake, rocmsmilib, and hwloc.
This upgrade also tests the version of existing component
builds to avoid rebuilding component.

build_aomp.sh now builds "prereq" as a component and no
longer builds hwloc, or rocmsmilib.  The scripts build_hwloc.sh
build_rocm_smi_lib.sh may now be deleted.

build_openmp.sh now gets hwloc from $AOMP_SUPP/hwloc
instead of the installation directory.

aomp_common_vars was changed to get CMAKE from AOMP_SUPP/cmake/bin/cmake
with a very descriptive error message if cmake cannot be found under
AOMP_SUPP or a system cmake. If an AOMP_SUPP cmake could not be found
and a system cmake is used, then a warning is printed.

We may move more components from the AOMP build and installation
into supplemental components to reduce compiler size.

More documentation changes are required.

diff --git a/bin/aomp_common_vars b/bin/aomp_common_vars
--- a/bin/aomp_common_vars
+++ b/bin/aomp_common_vars
@@ -102,10 +102,27 @@ CUDAT=${CUDAT:-$CUDA/targets}
 CUDAINCLUDE=${CUDAINCLUDE:-$CUDA/include}
 CUDABIN=${CUDABIN:-$CUDA/bin}
 
-if [ -f /usr/local/cmake/bin/cmake ] ; then
-  AOMP_CMAKE=${AOMP_CMAKE:-/usr/local/cmake/bin/cmake}
-else
-  AOMP_CMAKE=${AOMP_CMAKE:-cmake}
+# unless overridden with AOMP_CMAKE, get CMAKE from the
+# prerequisite supplemental component cmake.
+AOMP_CMAKE=${AOMP_CMAKE:-$AOMP_SUPP/cmake/bin/cmake}
+if [ ! -f $AOMP_CMAKE ] ; then
+  AOMP_CMAKE=`which cmake`
+  if [ "$AOMP_CMAKE" == "" ] ; then
+    echo "ERROR: finding cmake in aomp_common_vars."
+    echo "       Missing prerequisite supplemental component cmake."
+    echo "       Please run: ./build_prereq.sh cmake"
+    echo "       OR set AOMP_CMAKE env variable to a valid cmake binary"
+    echo "       OR build ALL prerequisite components with: ./build_prereq.sh"
+    echo
+    echo "NOTE:  All supplemental components are built and retrieved from "
+    echo "       subdirectories of the directory defined by environment variable"
+    echo "       AOMP_SUPP whose current value is: $AOMP_SUPP"
+    exit 1
+  else
+    # FIXME: Add version check here for system cmake.
+    echo "WARNING: Using system cmake $AOMP_CMAKE "
+    echo "         consider building cmake with: ./build_prereq.sh cmake"
+  fi
 fi
 
 AOMP_USE_NINJA=${AOMP_USE_NINJA:-0}
