Refactored patchrepo/removerepo to use patch control file. Cleanued up clone_aomp.sh as checkouts are no longer needed

diff --git a/bin/aomp_common_vars b/bin/aomp_common_vars
--- a/bin/aomp_common_vars
+++ b/bin/aomp_common_vars
@@ -221,47 +221,87 @@ function checkrepo(){
 function patchrepo(){
 if [ "$AOMP_APPLY_ROCM_PATCHES" == 1 ] ; then
    cd $patchdir
-   echo "Testing patch $patchfile to $patchdir"
-   applypatch="yes"
-   patch -p1 -t -N --dry-run <$patchfile >/dev/null
-   if [ $? != 0 ] ; then
-      applypatch="no"
-      # Check to see if reverse patch applies cleanly
-      patch -p1 -R --dry-run -t <$patchfile >/dev/null
-      if [ $? == 0 ] ; then
-         echo "patch $patchfile was already applied to $patchdir"
-      else
-         echo
-         echo "ERROR: Patch $patchfile will not apply"
-         echo "       cleanly to directory $patchdir"
-         echo "       Check if it was already applied."
-         echo
-         exit 1
-      fi
+   if [[ "$1" =~ "postinstall" ]]; then
+     getpatchlist $1
+   else
+     getpatchlist
    fi
-   if [ "$applypatch" == "yes" ] ; then
-      echo "Applying patch $patchfile to $patchdir"
-      patch -p1 --no-backup-if-mismatch <$patchfile
-   fi
+
+   #loop through list of patches to apply
+   for patch in $patches; do
+     patchfile=$patchloc/$patch
+     echo "Testing patch $patchfile to $patchdir"
+
+     applypatch="yes"
+     patch -p1 -t -N --dry-run <$patchfile >/dev/null
+     if [ $? != 0 ] ; then
+        applypatch="no"
+        # Check to see if reverse patch applies cleanly
+        patch -p1 -R --dry-run -t <$patchfile >/dev/null
+        if [ $? == 0 ] ; then
+           echo "patch $patchfile was already applied to $patchdir"
+        else
+           echo
+           echo "ERROR: Patch $patchfile will not apply"
+           echo "       cleanly to directory $patchdir"
+           echo "       Check if it was already applied."
+           echo
+           exit 1
+        fi
+     fi
+     if [ "$applypatch" == "yes" ] ; then
+        echo "Applying patch $patchfile to $patchdir"
+        patch -p1 --no-backup-if-mismatch <$patchfile
+     fi
+   done
 fi
+
 }
 
 function removepatch(){
 if [ "$AOMP_APPLY_ROCM_PATCHES" == 1 ] ; then
+   echo "Patchdir $patchdir"
    cd $patchdir
-   echo "Testing reverse patch $patchfile to $patchdir"
-   reversepatch="yes"
-   # Check to see if reverse patch applies cleanly
-   patch -p1 -R --dry-run -t <$patchfile >/dev/null
-   if [ $? != 0 ] ; then
-      echo "patch $patchfile was NOT applied $patchdir, no patch to reverse"
-      reversepatch="no"
-   fi
-   if [ "$reversepatch" == "yes" ] ; then
-      echo "Reversing patch $patchfile to $patchdir"
-      patch -p1 -R -t --no-backup-if-mismatch <$patchfile
-   fi
+   getpatchlist
+   echo "PATCHES TO REMOVE: $patches"
+   for patch in $patches; do
+     patchfile=$patchloc/$patch
+     echo "Testing reverse patch $patchfile to $patchdir"
+     reversepatch="yes"
+     # Check to see if reverse patch applies cleanly
+     patch -p1 -R --dry-run -f <$patchfile  >/dev/null
+     if [ $? != 0 ] ; then
+        echo "patch $patchfile was NOT applied $patchdir, no patch to reverse"
+        reversepatch="no"
+     fi
+     if [ "$reversepatch" == "yes" ] ; then
+        echo "Reversing patch $patchfile to $patchdir"
+        patch -p1 -R -f --no-backup-if-mismatch <$patchfile
+     fi
+   done
 fi
+}
+
+function getpatchlist(){
+   currdir=$(pwd)
+   basedir=$(basename $currdir)
+   if [[ "$1" =~ "postinstall" ]]; then
+     reporegex="(^$1:\s)"
+   else
+     reporegex="(^$basedir:\s)"
+   fi
+   controlfile=$patchloc/patch-control-file.txt
+   #read patch control file and look for correct patches
+   echo "$reporegex"
+   while read -r line; do
+   if [[ "$line" =~ $reporegex ]]; then
+     echo "$line"
+     #remove basename from list of patches
+     patches=${line/"${BASH_REMATCH[1]}"}
+     echo "patches: $patches"
+     break
+   fi
+   done < "$controlfile"
 }
 
 function help_build_aomp(){
