Move aomp 0.7-5 to ROCm 2.9, add patch to comgr to use old method for getting section name in llvm-9, move all patches to patches dir, added function patchrepo to aomp_common_vars and changed all build scripts that patch to use this function. minor change to clone_aomp.sh to undo previous patches to comgr.  Note: our llvm-project branch for llvm-9 was updated to support f16 so rocm-device-libs from ROCm 2.9 will now build cleanly.  Therefore, you must have the latest branch AOMP-191008 to build aomp 0.7-5

diff --git a/bin/aomp_common_vars b/bin/aomp_common_vars
--- a/bin/aomp_common_vars
+++ b/bin/aomp_common_vars
@@ -8,7 +8,7 @@
 AOMP_VERSION=${AOMP_VERSION:-"0.7"}
 AOMP_VERSION_MOD=${AOMP_VERSION_MOD:-"5"}
 AOMP_VERSION_STRING=${AOMP_VERSION_STRING:-"$AOMP_VERSION-$AOMP_VERSION_MOD"}
-ROCM_VERSION="2.7.22"
+ROCM_VERSION="2.9.22"
 export AOMP_VERSION_STRING AOMP_VERSION AOMP_VERSION_MOD ROCM_VERSION
 
 # set install directory and the link directory
@@ -104,23 +104,23 @@ AOMP_LLD_REPO_BRANCH=${AOMP_LLD_REPO_BRANCH:-release_80}
 AOMP_OPENMP_REPO_NAME=${AOMP_OPENMP_REPO_NAME:-openmp}
 AOMP_OPENMP_REPO_BRANCH=${AOMP_OPENMP_REPO_BRANCH:-release_80_AOMP_063}
 AOMP_LIBDEVICE_REPO_NAME=${AOMP_LIBDEVICE_REPO_NAME:-rocm-device-libs}
-AOMP_LIBDEVICE_REPO_BRANCH=${AOMP_LIBDEVICE_REPO_BRANCH:-roc-ocl-2.7.x}
+AOMP_LIBDEVICE_REPO_BRANCH=${AOMP_LIBDEVICE_REPO_BRANCH:-roc-ocl-2.9.x}
 AOMP_OCLRUNTIME_REPO_NAME=${AOMP_OCLRUNTIME_REPO_NAME:-rocm-opencl-runtime}
-AOMP_OCLRUNTIME_REPO_BRANCH=${AOMP_OCLRUNTIME_REPO_BRANCH:-roc-2.7.x}
+AOMP_OCLRUNTIME_REPO_BRANCH=${AOMP_OCLRUNTIME_REPO_BRANCH:-roc-2.9.x}
 AOMP_OCLDRIVER_REPO_NAME=${AOMP_OCLDRIVER_REPO_NAME:-rocm-opencl-driver}
-AOMP_OCLDRIVER_REPO_BRANCH=${AOMP_OCLDRIVER_REPO_BRANCH:-roc-2.7.x}
+AOMP_OCLDRIVER_REPO_BRANCH=${AOMP_OCLDRIVER_REPO_BRANCH:-roc-2.9.x}
 AOMP_OCLICD_REPO_NAME=${AOMP_OCLICD_REPO_NAME:-opencl-icd-loader}
 AOMP_OCLICD_REPO_BRANCH=${AOMP_OCLICD_REPO_BRANCH:-master}
 AOMP_HCC_REPO_NAME=${AOMP_HCC_REPO_NAME:-hcc}
-AOMP_HCC_REPO_BRANCH=${AOMP_HCC_REPO_BRANCH:-roc-2.7.x}
+AOMP_HCC_REPO_BRANCH=${AOMP_HCC_REPO_BRANCH:-roc-2.9.x}
 AOMP_HIP_REPO_NAME=${AOMP_HIP_REPO_NAME:-hip}
-AOMP_HIP_REPO_BRANCH=${AOMP_HIP_REPO_BRANCH:-roc-2.7.x}
+AOMP_HIP_REPO_BRANCH=${AOMP_HIP_REPO_BRANCH:-roc-2.9.x}
 AOMP_RINFO_REPO_NAME=${AOMP_RINFO_REPO_NAME:-rocminfo}
 AOMP_RINFO_REPO_BRANCH=${AOMP_RINFO_REPO_BRANCH:-master}
 AOMP_ROCT_REPO_NAME=${AOMP_ROCT_REPO_NAME:-roct-thunk-interface}
-AOMP_ROCT_REPO_BRANCH=${AOMP_ROCT_REPO_BRANCH:-roc-2.7.x}
+AOMP_ROCT_REPO_BRANCH=${AOMP_ROCT_REPO_BRANCH:-roc-2.9.x}
 AOMP_ROCR_REPO_NAME=${AOMP_ROCR_REPO_NAME:-rocr-runtime}
-AOMP_ROCR_REPO_BRANCH=${AOMP_ROCR_REPO_BRANCH:-roc-2.7.x}
+AOMP_ROCR_REPO_BRANCH=${AOMP_ROCR_REPO_BRANCH:-roc-2.9.x}
 AOMP_ATMI_REPO_NAME=${AOMP_ATMI_REPO_NAME:-atmi}
 AOMP_ATMI_REPO_BRANCH=${AOMP_ATMI_REPO_BRANCH:-aomp-0.7}
 AOMP_EXTRAS_REPO_NAME=${AOMP_EXTRAS_REPO_NAME:-aomp-extras}
@@ -128,7 +128,9 @@ AOMP_EXTRAS_REPO_BRANCH=${AOMP_EXTRAS_REPO_BRANCH:-0.7-5}
 AOMP_APPS_REPO_NAME=${AOMP_APPS_REPO_NAME:-openmpapps}
 AOMP_APPS_REPO_BRANCH=${AOMP_APPS_REPO_BRANCH:-AOMP-0.5}
 AOMP_COMGR_REPO_NAME=${AOMP_COMGR_REPO_NAME:-rocm-compilersupport}
-AOMP_COMGR_REPO_BRANCH=${AOMP_COMGR_REPO_BRANCH:-roc-2.7.x}
+AOMP_COMGR_REPO_BRANCH=${AOMP_COMGR_REPO_BRANCH:-roc-2.9.x}
+AOMP_F18_REPO_NAME=${AOMP_F18_REPO_NAME:-f18}
+AOMP_F18_REPO_BRANCH=${AOMP_F18_REPO_BRANCH:-master}
 AOMP_FLANG_REPO_NAME=${AOMP_FLANG_REPO_NAME:-flang}
 AOMP_FLANG_REPO_BRANCH=${AOMP_FLANG_REPO_BRANCH:-AOMP-191010}
 
@@ -179,6 +181,33 @@ function checkrepo(){
    if [ ! -d $REPO_DIR ] ; then
       echo "ERROR:  Missing repository directory $REPO_DIR"
       exit 1
+   fi
+}
+
+#  TO use this function set variables patchdir and patchfile
+function patchrepo(){
+   cd $patchdir
+   echo "Testing patch $patchfile to $patchdir"
+   applypatch="yes"
+   patch -p1 -t -N --dry-run <$patchfile >/dev/null
+   if [ $? != 0 ] ; then
+      applypatch="no"
+      # Check to see if reverse patch applies cleanly
+      patch -p1 -R --dry-run -t <$patchfile >/dev/null
+      if [ $? == 0 ] ; then
+         echo "patch $patchfile was already applied to $patchdir"
+      else
+         echo
+         echo "ERROR: Patch $patchfile will not apply"
+         echo "       cleanly to directory $patchdir"
+         echo "       Check if it was already applied."
+         echo
+         exit 1
+      fi
+   fi
+   if [ "$applypatch" == "yes" ] ; then
+      echo "Applying patch $patchfile to $patchdir"
+      patch -p1 <$patchfile
    fi
 }
 
