add support for ccache

diff --git a/trunk/trunk_common_vars b/trunk/trunk_common_vars
--- a/trunk/trunk_common_vars
+++ b/trunk/trunk_common_vars
@@ -53,12 +53,26 @@ if [ "$AOMP_USE_NINJA" == 0 ] ; then
   AOMP_NINJA_BIN="make"
 else
   AOMP_NINJA_BIN=`which ninja`
-  if [ AOMP_NINJA_BIN == "" ] ; then
+  if [ "$AOMP_NINJA_BIN" == "" ] ; then
     echo "ERROR: AOMP_USE_NINJA is $AOMP_USE_NINJA but no ninja bin found in PATH"
     echo "       Either install ninja in PATH or set AOMP_USE_NINJA=0"
     echo
     exit 1
   fi
+fi
+
+AOMP_USE_CCACHE=${AOMP_USE_CCACHE:-1}
+if [ "$AOMP_USE_CCACHE" == 0 ] ; then
+  AOMP_CCACHE_OPTS=""
+else
+  _ccache_bin=`which ccache`
+  if [ "$_ccache_bin" == "" ] ; then
+    echo "ERROR: AOMP_USE_CCACHE is $AOMP_USE_CCACHE but no ccache bin found in PATH"
+    echo "       Either install ccache or set AOMP_USE_CCACHE=0"
+    echo
+    exit 1
+  fi
+  AOMP_CCACHE_OPTS="-DCMAKE_C_COMPILER_LAUNCHER=$_ccache_bin -DCMAKE_CXX_COMPILER_LAUNCHER=$_ccache_bin"
 fi
 
 # AOMP_SUPP is for SUPPlemental software components needed for testing.
