the location of the ompd directory has changed.  This fix looks for both the old an new locations

diff --git a/test/hip-openmp/matrixmul_omp_for/do_debug b/test/hip-openmp/matrixmul_omp_for/do_debug
--- a/test/hip-openmp/matrixmul_omp_for/do_debug
+++ b/test/hip-openmp/matrixmul_omp_for/do_debug
@@ -6,10 +6,19 @@ if [ ! -f $hipcc_loc ]; then
   hipcc_loc=$AOMP/../bin/hipcc
 fi
 
+ompd_dir="$AOMP/share/gdb/python/ompd"
+if [ ! -d $ompd_dir ] ; then
+  ompd_dir="$AOMP/lib-debug/ompd"
+fi
+if [ ! -d $ompd_dir ] ; then
+  echo "ERROR ompd directory not found in $AOMP/share/gdb/python/ompd"
+  exit 1
+fi
+
 bldcmd="$hipcc_loc -O0 -g -ggdb  -fopenmp matrixmul.cpp -o matrixmul"
 #cgdb=`which cgdb` && [ "$cgdb" != "" ] && gdbcmd="$cgdb -d $gdbcmd"
 
-export LD_LIBRARY_PATH=$AOMP/lib-debug:$AOMP/lib
+export LD_LIBRARY_PATH=$AOMP/lib-debug:$AOMP/lib:$ompd_dir
 export OMP_DEBUG=enabled
 export OMP_NUM_THREADS=3
 
@@ -27,4 +36,4 @@ if [ ! -f $rocgdb ]; then
   rocgdb=$AOMP/../bin/rocgdb
 fi
 
-$rocgdb -x  "$AOMP/lib-debug/ompd/__init__.py" ./matrixmul -ex "source do_debug_command_file"
+$rocgdb -x "$ompd_dir/__init__.py" ./matrixmul -ex "source do_debug_command_file"
